### ISSUE TITLE
support Dayi in Fcitx5

### ISSUE THREAD

**Issue by ryanpig** [fcitx/fcitx5-table-extra#10]
The input method Dayi was supported in the old fcitx repository [fcitx-table-dayi](https://github.com/fcitx/fcitx-table-dayi). It would be nice to support it in fcitx5 as well. I could create a pull request to add relevant table, configuration file and icon.

**Comment by wengxt** [comment]
done. See https://github.com/fcitx/fcitx5-table-dayi/

**Comment by ryanpig** [comment]
Thanks! :)
