### ISSUE TITLE
在速成输入法(Quick Classic)的开始位置多了一些unicode乱码

### ISSUE THREAD

**Issue by mingzhong16** [fcitx/fcitx5-table-extra#21]
我主要是速成用家及使用Arch Linux

在fcitx5-table-extra的版本5.1.2-1及之后, 在速成(Quick Classic)有一些组合比如"OK", unicode乱码  ""会出现在列表的开始位置(位置1)
, "OH"在列表的开始位置会有另一个乱码""

但在5.1.1-1及之前, 组合"OK"是正常, 但另一个组合"YL"在开始位置(位置1)会多了个字"𥪕", 在速成列表是不存在
所以看来这个bug存在了一段时间, 不过未有人发现

我看了repo内quick-classic.txt的, 内里的次序是正常
不清楚是否在compile过程出了错, 而且也不清楚有没有其他输入法也有这个bug

**Comment by wengxt** [comment]
首先，5.1.2 到 5.1.1 根本没有修改过速成，最近的对速成的修改在 5.1.3。最新的版本是 5.1.4

其次，和你想像的正相反，最近对于速成的修改正是去除这些 PUA 字符

https://www.csslayer.info/wordpress/fcitx-dev/%e5%8e%bb%e9%99%a4-fcitx-5-%e7%a0%81%e8%a1%a8%e7%9a%84-pua-%e5%ad%97%e7%ac%a6/

在 5.1.2 及之前的 yl 从 yl ，被替换为了 yl 𥪕 是 pua 字符替换为正式的 unicode 字符，对应仓颉是 ythdl 并无问题。
https://www.zdic.net/hans/%F0%A5%AA%95 

在最新的 5.1.4 中，你贴的两个字已经更新为
ok 𠊷 和 oh 𢒑

如果你将系统更新到最新还有类似问题，请将 ~/.local/share/fcitx5/table/quick-classic.user.dict 发来看看

**Comment by wengxt** [comment]
也许你曾经输入过这两个字（虽然我很难想象因为看起来都是很生僻的字），然后老的编码被存储到了 user dict 当中，然后因为系统字体更新的缘故原有的 pua 区字符不能再显示导致你认为乱码了

**Comment by mingzhong16** [comment]
的确是user dict的问题, 删除了user dict就可以了
虽然不清楚为何会存储了这些字

非常感谢解答🙏🙏
