### ISSUE TITLE
how to install this package? (debian-like)

### ISSUE THREAD

**Issue by overseers-desk** [fcitx/fcitx5-table-extra#4]
Using PureOS which is based on Debian (customised by the laptop vendor).

Successfully installed fcitix5 and fcitx5-tables, and now I can type in PinYin, but debian's packaging system doesn't have fcitx5-table-extra. At first, I thought I can just copy ./tables from this repo to /usr/share/fcitx5 but it doesn't work - restarting fcitx5 and fcitx5-config-qt does not show any of the new input methods added by copying tables directory over.

Kindly advise how to let fcitx5 recognise the new tables.

**Comment by wengxt** [comment]
./tables files are text format, not binary format. You can use cmake to build and install them, https://fcitx-im.org/wiki/Compile_from_source.

**Comment by samwhelp** [comment]
Please refer my [demo](https://github.com/samwhelp/demo-forum-case/tree/main/demo/fcitx5-table-extra) for build deb.
